const images = {
  icon: require('./images/icon.png'),
  square: require('./images/placeholder_sq.png'),
  rectangle: require('./images/placeholder_rct.png'),
  search: require('./images/search.png'),
  backArrow: require('./images/backArrow.png'),
  logoHeader: require('./images/logoHeader.png'),
  loginHappyFace: require('./images/loginHappyFace.png'),
  passVisibility: require('./images/passVisibility.png'),
  facebook: require('./images/facebook.png'),
  star: require('./images/star.png'),
  share: require('./images/share.png'),
  news: require('./images/now.png'),
  entertaiment: require('./images/enterteinment.png'),
  culture: require('./images/culture.png'),
  politics: require('./images/politics.png'),
  virals: require('./images/virals.png'),
  redChronicle: require('./images/redChronicles.png'),
  kitchen: require('./images/kitchen.png'),
  internationalNews: require('./images/international.png'),
  sports: require('./images/sports.png'),
  health: require('./images/health.png'),
  business: require('./images/business.png'),
  facebookSocial: require('./images/social-media-facebook.png'),
  reddit: require('./images/social-media-reddit.png'),
  linkedin: require('./images/social-media-linkedin.png'),
  mail: require('./images/social-media-mail.png'),
  googleSocial: require('./images/social-media-google.png'),
  pinterest: require('./images/social-media-pinterest.png'),
  imgNews: require('./images/img-home-noticias-no-clasificadas.jpg'),
  imgHomeBanner: require('./images/img-home-banner-principal.jpg'),
  degrad: require('./images/degradado-fondo-virales-01.png'),
  imgShark: require('./images/img-home-seccion-noticia.jpg'),
};

export default images;
